# Generated by Django 4.2.20 on 2025-04-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_listed',
            field=models.BooleanField(default=False),
        ),
    ]
