# Generated by Django 4.2.20 on 2025-04-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0002_item_is_listed'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
