# Generated by Django 4.2.20 on 2025-04-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0003_item_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='listing_duration',
            field=models.IntegerField(default=0),
        ),
    ]
