name: Django CI

on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: accessing secrets
      run: |
        echo "KLIP_PREPARE_URL=${{ secrets.KLIP_PREPARE_URL }}" >> .env
        echo "KLIP_REQUEST_URL=${{ secrets.KLIP_REQUEST_URL }}" >> .env
        echo "KLIP_RESULT_URL=${{ secrets.KLIP_RESULT_URL }}" >> .env
        echo "ADMIN_ADDRESS=${{ secrets.ADMIN_ADDRESS }}" >> .env
        echo "ADMIN_PRIVATE_KEY=${{ secrets.ADMIN_PRIVATE_KEY }}" >> .env
        echo "NFT_CONTRACT_ADDRESS=${{ secrets.NFT_CONTRACT_ADDRESS }}" >> .env
        echo "KLAYTN_RPC_URL=${{ secrets.KLAYTN_RPC_URL }}" >> .env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
        echo "BAPP_NAME=${{ secrets.BAPP_NAME }}" >> .env
    - name: Run Tests
      run: |
        python manage.py test