name: Django Deploy

on:
  workflow_run:
    workflows: ["Django CI"]
    types:
      - completed
    branches: [ "release" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: excuting remote ssh commands
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.PRIVATE_KEY }} 
        port: 22
        script: |
          cd /home/ubuntu/nft_project
          source venv/bin/activate
          cd /home/ubuntu/nft_project
          pip install -r requirements.txt
          echo "< requirements.txt installed >"
          git pull origin release
          echo "< pulled completed >"
          nohup python manage.py runserver 0.0.0.0:8000 &
