name: Django Deploy

on:
  workflow_run:
    workflows: ["Django CI"]
    branches:
      - release
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: excuting remote ssh commands
      uses: appleboy/ssh-action@v0.1.10
      env:
          SECRET_KEY: ${{ secrets.PRIVATE_KEY }}
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.PRIVATE_KEY }} 
        port: 22
        script: |
          cd /home/ubuntu/nft_project
          source venv/bin/activate
          cd /home/ubuntu/nft_project
          pip install -r requirements.txt
          echo "< requirements.txt installed >"
          git pull origin release
          echo "< pulled completed >"
          echo "KLIP_PREPARE_URL=${{ secrets.KLIP_PREPARE_URL }}" >> .env
          echo "KLIP_REQUEST_URL=${{ secrets.KLIP_REQUEST_URL }}" >> .env
          echo "KLIP_RESULT_URL=${{ secrets.KLIP_RESULT_URL }}" >> .env
          echo "ADMIN_ADDRESS=${{ secrets.ADMIN_ADDRESS }}" >> .env
          echo "ADMIN_PRIVATE_KEY=${{ secrets.ADMIN_PRIVATE_KEY }}" >> .env
          echo "NFT_CONTRACT_ADDRESS=${{ secrets.NFT_CONTRACT_ADDRESS }}" >> .env
          echo "KLAYTN_RPC_URL=${{ secrets.KLAYTN_RPC_URL }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "BAPP_NAME=${{ secrets.BAPP_NAME }}" >> .env
          echo "{\"SECRET_KEY\": \"$SECRET_KEY\"}" > secrets.json
          echo "< secrets.json file created >"
          python manage.py makemigrations
          python manage.py migrate
          python manage.py runserver 0.0.0.0:8000 &
