name: Django Deploy

on:
  workflow_run:
    workflows: ["Django CI"]
    types:
      - completed
    branches: [ "release" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: excuting remote ssh commands
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.PRIVATE_KEY }} 
        port: 22
        script: |
          cd /home/ubuntu/nft_project
          git checkout release
          git pull origin release
          sudo systemctl restart uwsgi